# Generated by Django 4.0.3 on 2022-05-14 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='team_id',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='user_id',
            new_name='user',
        ),
    ]
