# Generated by Django 4.0.3 on 2022-05-14 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_supplier_rename_size_task_priority_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gantt',
            old_name='subtask_id',
            new_name='subtask',
        ),
        migrations.RenameField(
            model_name='rawmaterial',
            old_name='supplier_id',
            new_name='supplier',
        ),
        migrations.RenameField(
            model_name='rawmaterial',
            old_name='task_id',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='subtask',
            old_name='task_id',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='project_id',
            new_name='project',
        ),
    ]
