# Generated by Django 4.0.3 on 2022-05-23 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
    ]
