# Generated by Django 4.0.3 on 2022-05-26 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_remove_task_priority_remove_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterial',
            name='description',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='rawmaterial',
            name='task',
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
            preserve_default=False,
        ),
    ]
