# Generated by Django 4.0.3 on 2022-06-07 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_task_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user_id',
            new_name='user',
        ),
    ]
