# Generated by Django 4.0.3 on 2022-06-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(default='/login', max_length=100),
            preserve_default=False,
        ),
    ]
